
services:
  redis: # Redis service configuration
    image: redis:alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data   # Persist Redis data in a named volume defined below

  redisdemo: # ASP.NET Core application service configuration
    build:
      context: .
      dockerfile: RedisDemo/Dockerfile
    container_name: redisdemoservice
    ports:
      - "5000:8080"
      - "5443:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Release
      - ASPNETCORE_HTTP_PORTS=8080  # This will make the .NET app listen on port 8080 for HTTP traffic
      - ASPNETCORE_HTTPS_PORTS=8081  # This will make the .NET app listen on port 8081 for HTTPS traffic
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx # Path inside the container where the certificate will be mounted
      - ASPNETCORE_Kestrel__Certificates__Default__Password=MyPassword123! # Password for the certificate, should match the one used when creating the .pfx file
      - DOTNET_RUNNING_IN_CONTAINER=true
    volumes:
      - C:/certs:/https:ro # Mount host directory with certs to container (read-only), simply for copying the data and not using any volume managed by Docker
    depends_on:
      - redis
    restart: always
    

volumes:
  redis_data:   # Define a named volume for Redis data persistence managed by Docker automatically, no need to specify anything else here
