name: CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted   # 👈 This ensures it runs on your Windows runner
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Build
        run: dotnet build ./RedisDemo/RedisDemo.csproj --configuration Release
